# Generated by Django 4.2.1 on 2024-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(blank=True, max_length=45, null=True)),
                ('ner', models.CharField(blank=True, max_length=1024, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('answer_image', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbot',
                'db_table': 'Chatbot train data',
            },
        ),
    ]
