# Generated by Django 5.0.4 on 2024-04-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('new_club', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberName',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='student_num',
        ),
        migrations.RemoveField(
            model_name='boardpostcontent',
            name='post_id',
        ),
        migrations.CreateModel(
            name='ClubMemberList',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.IntegerField()),
                ('club_name', models.ForeignKey(db_column='club_name', on_delete=django.db.models.deletion.CASCADE, to='club_member.clubmembers')),
                ('student_num', models.ForeignKey(db_column='student_num', on_delete=django.db.models.deletion.CASCADE, to='club_member.membername')),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='BoardPost',
        ),
        migrations.DeleteModel(
            name='BoardPostContent',
        ),
    ]
