# Generated by Django 5.0.4 on 2024-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_member', '0002_clubmembers_membername_remove_clubmember_club_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmemberlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clubmembers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='membername',
            options={'managed': False},
        ),
    ]
