# Generated by Django 3.2 on 2024-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0001_initial'),
        ('club_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='club_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club'),
        ),
    ]
