# Generated by Django 4.2.1 on 2024-05-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0006_remove_clubmember_club_name_alter_club_logo_and_more'),
        ('club_board', '0002_alter_board_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='club_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club'),
        ),
    ]
