# Generated by Django 4.2.1 on 2024-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_board', '0003_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='id',
        ),
        migrations.AddField(
            model_name='notice',
            name='specific_id',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
