# Generated by Django 4.2.1 on 2024-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_board', '0004_remove_notice_id_notice_specific_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
