# Generated by Django 4.2.1 on 2024-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원들'},
        ),
    ]
