# Generated by Django 4.2.1 on 2024-05-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_account', '0002_alter_customuser_options'),
        ('club_account', '0002_alter_customuser_options_alter_customuser_gender'),
    ]

    operations = [
    ]
