# Generated by Django 5.0.4 on 2024-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.TextField()),
                ('category', models.BooleanField()),
                ('introducation', models.TextField()),
                ('photo', models.TextField()),
                ('logo', models.TextField()),
                ('new_club', models.BooleanField()),
            ],
        ),
    ]
