# Generated by Django 3.2 on 2024-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='club_photos')),
                ('logo', models.ImageField(null=True, upload_to='club_logos')),
                ('new_club', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '동아리',
                'verbose_name_plural': '동아리들',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField()),
                ('joined_date', models.DateTimeField()),
                ('job', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '동아리 회원',
                'verbose_name_plural': '동아리 회원들',
            },
        ),
    ]
