# Generated by Django 4.2.1 on 2024-05-14 11:36

import club_introduce.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to=club_introduce.models.club_photo_directory_path)),
                ('logo', models.ImageField(null=True, upload_to=club_introduce.models.club_logo_directory_path)),
                ('new_club', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '동아리',
                'verbose_name_plural': '동아리들',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField()),
                ('job', models.CharField(default='일반회원', max_length=5)),
                ('club_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='student_id')),
            ],
            options={
                'verbose_name': '동아리 회원',
                'verbose_name_plural': '동아리 회원들',
            },
        ),
    ]
