# Generated by Django 5.0.4 on 2024-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubList',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('introduction', models.TextField()),
                ('photo', models.ImageField(upload_to='club_photos')),
                ('logo', models.ImageField(upload_to='club_logos')),
                ('new_club', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Club_Introduce',
        ),
    ]
