# Generated by Django 4.2.1 on 2024-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(default='sports', max_length=20),
            preserve_default=False,
        ),
    ]
