# Generated by Django 5.0.4 on 2024-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Join',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_name', models.TextField()),
                ('student_num', models.IntegerField()),
                ('join_data', models.TextField(null=True)),
                ('job', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='club_introduce',
            name='id',
        ),
        migrations.AlterField(
            model_name='club_introduce',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='club_introduce',
            name='club_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club_introduce',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='club_introduce',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
