# Generated by Django 5.0.4 on 2024-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0002_clublist_delete_club_introduce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clublist',
            options={'managed': False},
        ),
    ]
