# Generated by Django 4.2.1 on 2024-04-25 05:54

import club_introduce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0002_auto_20240422_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(null=True, upload_to=club_introduce.models.club_photo_directory_path),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(null=True, upload_to=club_introduce.models.club_logo_directory_path),
        ),
    ]
