# Generated by Django 5.0.4 on 2024-04-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0002_club_join_remove_club_introduce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_join',
            name='club_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club_introduce'),
        ),
        migrations.CreateModel(
            name='Board_Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.TextField()),
                ('writer', models.TextField()),
                ('create_date', models.TextField()),
                ('category', models.IntegerField()),
                ('recommend_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('club_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club_introduce')),
            ],
        ),
    ]
