# Generated by Django 5.0.4 on 2024-04-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0003_alter_club_join_club_name_board_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Post_Content',
            fields=[
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='club_introduce.board_post')),
                ('post_content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='board_post',
            name='club_type',
            field=models.ForeignKey(db_column='club_type', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club_introduce'),
        ),
        migrations.AlterField(
            model_name='club_join',
            name='club_name',
            field=models.ForeignKey(db_column='club_name', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club_introduce'),
        ),
        migrations.CreateModel(
            name='Board_Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('created_data', models.TextField()),
                ('writer', models.TextField()),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.board_post')),
            ],
        ),
        migrations.AlterField(
            model_name='club_join',
            name='student_num',
            field=models.ForeignKey(db_column='student_num', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.user'),
        ),
    ]
