# Generated by Django 4.2.1 on 2024-04-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0003_alter_club_logo_alter_club_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
    ]
