# Generated by Django 5.0.4 on 2024-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0004_board_post_content_user_alter_board_post_club_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_comment',
            name='created_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='board_post',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='club_join',
            name='join_data',
            field=models.DateTimeField(null=True),
        ),
    ]
