# Generated by Django 4.2.1 on 2024-05-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0003_alter_club_logo_alter_club_photo'),
        ('club_introduce', '0004_alter_clubmember_joined_date'),
    ]

    operations = [
    ]
