# Generated by Django 5.0.4 on 2024-04-15 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0005_alter_board_comment_created_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('new_club', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='board_post',
            name='club_type',
            field=models.ForeignKey(db_column='club_type', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club'),
        ),
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('join_data', models.DateField(null=True)),
                ('job', models.IntegerField()),
                ('club_name', models.ForeignKey(db_column='club_name', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club')),
                ('student_num', models.ForeignKey(db_column='student_num', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Club_Join',
        ),
        migrations.DeleteModel(
            name='Club_Introduce',
        ),
    ]
