# Generated by Django 4.2.1 on 2024-05-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0006_remove_clubmember_club_name_alter_club_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='club',
            new_name='club_name',
        ),
    ]
