# Generated by Django 4.2.1 on 2024-05-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0006_remove_clubmember_club_name_alter_club_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='club_name',
            field=models.ForeignKey(default='FreeBoard', on_delete=django.db.models.deletion.CASCADE, to='club_introduce.club'),
            preserve_default=False,
        ),
    ]
