# Generated by Django 5.0.4 on 2024-04-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0007_rename_board_comment_boardcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='join_data',
        ),
        migrations.AddField(
            model_name='boardpost',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='created_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='club_type',
            field=models.ForeignKey(db_column='club_type', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='club_introduce.club'),
        ),
    ]
