# Generated by Django 5.0.4 on 2024-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0009_alter_boardpost_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='created_data',
            field=models.DateTimeField(null=True),
        ),
    ]
