# Generated by Django 5.0.4 on 2024-04-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0010_alter_boardcomment_created_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardcomment',
            table='club_introduce_board_comment',
        ),
    ]
