# Generated by Django 5.0.4 on 2024-04-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0011_alter_boardcomment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardComment',
        ),
    ]
