# Generated by Django 5.0.4 on 2024-04-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('new_club', models.BooleanField()),
            ],
            options={
                'db_table': 'Club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.IntegerField()),
            ],
            options={
                'db_table': 'Club_Member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.TextField()),
                ('writer', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.IntegerField()),
                ('recommend_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('club_type', models.ForeignKey(db_column='club_type', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='club_information.club')),
            ],
            options={
                'db_table': 'Board_Post',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BoardPostContent',
            fields=[
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='club_information.boardpost')),
                ('post_content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Board_Post_Content',
                'managed': True,
            },
        ),
    ]
