# Generated by Django 4.2.1 on 2024-04-23 14:42

import club_information.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '사집첩, 이벤트',
                'verbose_name_plural': '사진첩, 이벤트 정보',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=club_information.models.club_logo_diretory_path)),
                ('photo', models.ImageField(upload_to=club_information.models.club_photo_diretory_path)),
            ],
            options={
                'verbose_name': '동아리 홈',
                'verbose_name_plural': '동아리 홈 정보',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '동아리 회원',
                'verbose_name_plural': '동아리 회원 정보',
                'managed': False,
            },
        ),
    ]
