# Generated by Django 5.0.4 on 2024-04-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubHome',
            fields=[
                ('club_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('introducation', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('new_club', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubHomeMember',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.IntegerField()),
                ('club_name', models.ForeignKey(db_column='club_name', default='Club1', on_delete=django.db.models.deletion.CASCADE, to='club_information.clubhome')),
            ],
        ),
        migrations.CreateModel(
            name='ClubHomePost',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.TextField()),
                ('writer', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.IntegerField()),
                ('recommend_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('club_type', models.ForeignKey(db_column='club_type', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='club_information.clubhome')),
            ],
        ),
        migrations.CreateModel(
            name='ClubHomeUser',
            fields=[
                ('student_num', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='boardpost',
            name='club_type',
        ),
        migrations.RemoveField(
            model_name='boardpostcontent',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='ClubHomePostContent',
            fields=[
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='club_information.clubhomepost', unique=True)),
                ('post_content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='clubhomemember',
            name='student_num',
            field=models.ForeignKey(db_column='student_num', default='1', on_delete=django.db.models.deletion.CASCADE, to='club_information.clubhomeuser'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='BoardPost',
        ),
        migrations.DeleteModel(
            name='BoardPostContent',
        ),
    ]
