# Generated by Django 4.2.1 on 2024-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_information', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumEvent',
        ),
    ]
