# Generated by Django 4.2.1 on 2024-05-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_information', '0002_delete_albumevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
