# Generated by Django 5.0.4 on 2024-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_information', '0002_clubhome_clubhomemember_clubhomepost_clubhomeuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubhome',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clubhomemember',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clubhomepost',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clubhomepostcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clubhomeuser',
            options={'managed': False},
        ),
    ]
