# Generated by Django 5.0.4 on 2024-04-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0006_club_alter_board_post_club_type_club_member_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board_Comment',
            new_name='BoardComment',
        ),
        migrations.RenameModel(
            old_name='Board_Post',
            new_name='BoardPost',
        ),
        migrations.RenameModel(
            old_name='Board_Post_Content',
            new_name='BoardPostContent',
        ),
        migrations.RenameModel(
            old_name='Club_Member',
            new_name='ClubMember',
        ),
        migrations.AlterModelTable(
            name='boardcomment',
            table='Board_Comment',
        ),
        migrations.AlterModelTable(
            name='boardpost',
            table='Board_Post',
        ),
        migrations.AlterModelTable(
            name='boardpostcontent',
            table='Board_Post_Content',
        ),
        migrations.AlterModelTable(
            name='club',
            table='Club',
        ),
        migrations.AlterModelTable(
            name='clubmember',
            table='Club_Member',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
