# Generated by Django 5.0.4 on 2024-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_introduce', '0008_remove_boardpost_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
